### ISSUE TITLE
Global Contexts in L0

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/level-zero-spec#57] opened 2023-01-08 21:46 UTC
L0 objects should be created with a specific context, and with that we maintain isolation of resources.

However, main issue on multi-library scenarios, is that we have objects being passed between libraries (like USM allocations), from one library to another, but the context is not known.

One possible solution is to return the context so a library can create a queue or list based on that context:

```cpp
// MPI receives USM pointer from another library
zeMemGetAllocProperties(..., &zeContext);
// now use the context to create the queue and list
zeCommandQueueCreate(zeContext, ...)
zeCommandListCreate(zeContext, ...)
...
```

however, with this, libraries are forced to have lazy initialization of resources. To allow having eager initialization of resources, something like an **L0 Global Context** is needed, so libraries can use USM pointers with L0 objects created with any other context, like queues and lists.

So, should we define an L0 global context? we could have something like

```cpp
zeDriverGetGlobalContext(hDriver, &hContext);
```
and when using that context, L0 doesnt enforce separation of resources, allowing USM pointers to be used with lists, queues, and other USM allocations created with any context,

CC: @zackwaters , @wdamon-intel , @bashbaug .

**Comment by cbelusar** [comment] 2023-01-13 16:50
We (communication libraries team) have concerns about this requirement. Can you involve us in design discussions going forward involving this proposal? 
Please include ( Alex Brooks - @abrooks98, Gengbin Zheng - @zhenggb72, Anatoliy Rozanov - @irozanova, Dmitry Durnov - @ddurnov )

**Comment by wdamon-intel** [comment] 2023-01-13 20:16
Instead of global context, one proposal is to make it possible to associate one or more contexts with a shared context group, via a new interface:

```c
// Define a shared context group of existing contexts
//
// hDriver, nonnull, handle to the driver object
// pCount, nonnull, number of contexts in the array of context handles
// phContexts, nonnull, array of context handles to associate within a context share-group
// phContextShared, nullable, pointer to the handle of the associated context share-group found or created by the runtime
ze_result_t zeContextSharedGet(ze_driver_handle_t hDriver, uint32_t *pCount, ze_context_handle_t *phContexts, ze_context_shared_handle_t *phContextShared); 

// Add a context to an existing shared context group
ze_result_t zeContextSharedAddContext(ze_context_shared_handle_t hContextShared, ze_context_handle_t hContext);

// Get the share-group of a context.
// Returns a null pointer in phContextShared if the context is not part of a share-group.
ze_result_t zeContextGetContextShared(ze_context_handle_t hContext, ze_context_shared_handle_t *phContextShared);
```

This interface would enable the application or a library to explicitly associate one or more contexts as peers, at any point in time, for the purpose of sharing L0 objects. The expectation is that once the shared context group is established, any L0 object owned by one context in the group would be usable by any other. Ownership of L0 objects is not transferred, however.

It is expected that the L0 objects would be used as they are today through the existing APIs.

Additionally, a context could only belong to one share-group, and once associated with a share-group the context would remain a part of that share-group for the lifetime of the context.  It would be an error to try to add a context to more than one shared context group.

Would something along these lines be satisfactory?

**Comment by irozanova** [comment] 2023-01-18 10:27
Hi @wdamon-intel,

The idea looks good to me, but does not it break a concept of separating resources? If anyone can add a context to a shared group and then use any L0 objects, then why do we need a separation of resources? 
In addition, shared groups require adding of the ability to get a context from USM pointer. (zeMemGetAllocProperties(..., &zeContext)).

As an advantage of shared groups I see is that it does not require any changes on application level, while global contexts require calling of zeDriverGetGlobalContext on application level and if application does not use zeDriverGetGlobalContext, then we still need an ability to get a context from USM pointer.

**Comment by jandres742** [comment] 2023-01-18 19:16
@irozanova thanks.

> In addition, shared groups require adding of the ability to get a context from USM pointer. (zeMemGetAllocProperties(..., &zeContext)).

correct. We are thinking on adding also the ability to return the context handle for a USM pointer

and you are also correct that if we use shared contexts, so what the point is of separation of resources. So idea here is to support all cases, and let the application decide what to do. Using contexts to separate resources may work for some applications, specially those porting from other APIs, like OpenCL, where similar concept exists, while using shared contexts may work more for others, like applications with multiple libraries executing, where flexibility on sharing resources is desired.

**Comment by irozanova** [comment] 2023-01-30 10:38
> Using contexts to separate resources may work for some applications, specially those porting from other APIs, like OpenCL

Will libraries be able to use shared contexts for that applications?

**Comment by wdamon-intel** [comment] 2023-01-30 17:56
> Will libraries be able to use shared contexts for that applications?

Hi @irozanova , yes that is a major motivator for this feature request/discussion.

**Comment by jandres742** [comment] 2023-03-09 20:32
@irozanova  do you think the interfaces proposed by @wdamon-intel  addresses your comments, or is there any additional feedback from your side?

**Comment by irozanova** [comment] 2023-03-13 10:02
Yes, the interfaces look good to me. Now I am thinking about performance. Calling zeContextGetContextShared and zeContextSharedAddContext will add additional latency to each MPI call. So, the solution zeMemGetAllocProperties(..., &zeContext) looks better since we already call zeMemGetAllocProperties

**Comment by jandres742** [comment] 2023-03-22 17:29
hi @irozanova 
instead of having shared-contexts, another possibility is to have APIs to export and import a resource into another context. Basically:

```cpp
zeContextExportResource(hContext, *void handle)
the USM pointer or handle passed as void is marked by current library as exportable,
meaning that it can be imported by other contexts.

zeContextImportResource(hContext, *void handle)
the USM pointer or handle passed as void is imported into the context to be used with
any resource created with it.
```

for instance, SYCL would create a USM device allocation and mark it as exportable, and then IMPI when receiving that pointer, will import it into the context it wants to use it with. This provides more fine granularity to which resources are being shared between several contexts.

With these, we dont need an API for getting a context with zeMemGetAllocProperties, but we could keep it if needed.

what do you think of these import/export APIs ?

**Comment by irozanova** [comment] 2023-03-24 09:28
Hi @jandres742,

The new API looks good to me. I think we can use it instead of shared contexts. A few questions:
1. From performance standpoint, would be zeContextImportResource a lightweight operation? We will have to call zeContextImportResource each time when IMPI receiving GPU pointer. So, it can add us additional latency.  
From performance standpoint, getting context from zeMemGetAllocProperties still looks better, since we already call this function each time.
2. Will we be able to call zeContextImportResource for the same pointer several times? I mean should we monitor on IMPI side that we already import this recourse before? 
3. I still see a problem if the pointer was not marked as exportable. For example it could be old SYCL version or the users allocated the memory themselves. In this case we need an ability to check if the memory is exportable and if it is not exportable , then we still need an ability to get context from zeMemGetAllocProperties

**Comment by MichalMrozek** [comment] 2023-03-24 09:41
1. First import may be more costly as it may require residency changes, subsequent imports would be fast 
2. For simplicity this could be allowed , othwersie you would need to track this in upper layers and driver would already do this bookkeeping for you and optimize the call
3. can you share what context you want to extract here ? zeMemGetAllocProperties already requires context as a parameter.

**Comment by irozanova** [comment] 2023-03-24 11:03
1-2. ok, thanks! It looks good to me. 
3. There was a proposal, that zeMemGetAllocProperties or any other function would return us a context from the pointer. If the user did not mark a context as exportable, then we need an ability to get an original context from the pointer.

**Comment by MichalMrozek** [comment] 2023-03-24 11:58
"3. There was a proposal, that zeMemGetAllocProperties or any other function would return us a context from the pointer. If the user did not mark a context as exportable, then we need an ability to get an original context from the pointer."

I don't think we can do this as one pointer may be present in many contexts.

**Comment by jandres742** [comment] 2023-03-24 16:48
> "3. There was a proposal, that zeMemGetAllocProperties or any other function would return us a context from the pointer. If the user did not mark a context as exportable, then we need an ability to get an original context from the pointer."
> 
> I don't think we can do this as one pointer may be present in many contexts.

@MichalMrozek when the USM allocation is created, it is against at specific context (the context passed wit zeMemAlloc). So idea here is to return it also in a new interface, zeMemGetAllocPropertiesExp. The context currently passed to zeMemGetAllocProperties is just an in, not an output, so it cannot be modified to return a value.

```cpp
///////////////////////////////////////////////////////////////////////////////
/// @brief Retrieves attributes of a memory allocation
/// 
/// @details
///     - This is an experimental function that extends
///       ::zeMemGetAllocProperties by returning
///       also the context used to create the allocation, in addition to all the properties
///       that ::zeMemGetAllocProperties typically returns.
///     - The application may call this function from simultaneous threads.
///     - The application may query attributes of a memory allocation unrelated
///       to the context.
///       When this occurs, the returned allocation type will be
///       ::ZE_MEMORY_TYPE_UNKNOWN, and the returned identifier and associated
///       device is unspecified.
/// 
/// @returns
///     - ::ZE_RESULT_SUCCESS
///     - ::ZE_RESULT_ERROR_UNINITIALIZED
///     - ::ZE_RESULT_ERROR_DEVICE_LOST
///     - ::ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY
///     - ::ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY
///     - ::ZE_RESULT_ERROR_INVALID_NULL_HANDLE
///         + `nullptr == hContext`
///     - ::ZE_RESULT_ERROR_INVALID_NULL_POINTER
///         + `nullptr == ptr`
///         + `nullptr == pMemAllocProperties`
ZE_APIEXPORT ze_result_t ZE_APICALL
zeMemGetAllocPropertiesExp(
    ze_context_handle_t hContext,                   ///< [in] handle of the context object
    const void* ptr,                                ///< [in] memory pointer to query
    ze_memory_allocation_properties_t* pMemAllocProperties, ///< [in,out] query result for memory allocation properties
    ze_context_handle_t* phContext,                 ///< [out][optional] context associated with this allocation
    ze_device_handle_t* phDevice                    ///< [out][optional] device associated with this allocation
    );
```

**Comment by MichalMrozek** [comment] 2023-03-27 05:51
But without context you will not be able to deduce to which device the actual pointer corresponds.
In mulitple root device scenarios (with multiple driver instances) , you may have the same device USM pointer on many devices.
You need context as input parameter to find proper object data.

**Comment by irozanova** [comment] 2023-10-06 13:41
Hi @MichalMrozek,

> you may have the same device USM pointer on many devices

Did you mean that we may have the same virtual address that can point to multiple physical addresses on different devices? Could you please explain how it is possible? I thought that a process has its own virtual address space and each virtual address can point only to one physical memory.

**Comment by MichalMrozek** [comment] 2023-10-06 15:14
You are right each process has its own virtual address space.

I was referring for scenario where you use a single process but you work with multiple devices.

**Comment by MichalMrozek** [comment] 2023-10-06 15:19
"
And another question how it works right now if we can provide any context to zeMemGetAllocProperties and it returns us proper device."

We extract the driver from the context that you pass and browse this driver instance for the pointer.
You may have multiple drivers in the system i.e. one for DG2 and another for integrated part.
On those different drivers you may have the same GPU VA for device USM that would be backed by different physical memory.

So passing any context to extract the USM data is incorrect, you need to pass context at least associated with the driver instance used to allocate USM memory.

**Comment by irozanova** [comment] 2023-10-09 09:10
> you need to pass context at least associated with the driver instance used to allocate USM memory

Thanks! This requirement is ok for Intel MPI, because we know the driver. So, zeMemGetAllocPropertiesExp function may look like:
```
zeMemGetAllocPropertiesExp(
    ze_driver_handle_t hDriver,                     ///< [in] handle of the driver object
    const void* ptr,                                ///< [in] memory pointer to query
    ze_memory_allocation_properties_t* pMemAllocProperties, ///< [in,out] query result for memory allocation properties
    ze_context_handle_t* phContext,                 ///< [out][optional] context associated with this allocation
    ze_device_handle_t* phDevice                    ///< [out][optional] device associated with this allocation
);
```

**Comment by vinser52** [comment] 2023-10-09 12:50
Hi @MichalMrozek,

We are working on a Unified Memory Framework (UMF) library that abstracts memory allocations and provides interop capabilities for other runtimes. For memory allocations, UMF resides between Unified Runtime and L0, CUDA, etc. drivers. One of the main use cases for interop is IMPI. E.g. SYCL or OpenMP allocates GPU memory via UR->UMF->GPU Driver, and UMF supports mapping between VA to corresponding memory pool. So that, IMPI can easily get IPC handles, or other memory properties for VA allocated via UMF.

I want to clarify this statement:
> On those different drivers you may have the same GPU VA for device USM that would be backed by different physical memory.

Does it mean that inside a single process, we might have two device pointers with the same VA but backed by different physical locations? If so I think it breaks the idea of USM when common VA space is used for host, device, and shared allocations.

**Comment by MichalMrozek** [comment] 2023-10-09 13:24
"
Does it mean that inside a single process, we might have two device pointers with the same VA but backed by different physical locations? If so I think it breaks the idea of USM when common VA space is used for host, device, and shared allocations."

Can you share some references to this idea of USM ?

**Comment by vinser52** [comment] 2023-10-09 14:12
SYCL spec: https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_unified_addressing

Tells that "Unified Addressing guarantees that all devices will use a unified address space."

L0 spec looks more strict: https://spec.oneapi.io/level-zero/latest/core/PROG.html#memory-and-images

It says that: "Memory is visible to the upper-level software stack as unified memory with a single virtual address space covering both the Host and **a specific device**."

Does "a specific device" mean exactly what you said? Anyway I think it is a significant limitation and looks like it does not conform SYCL spec. Thoughts?

**Comment by MichalMrozek** [comment] 2023-10-10 08:26
"
Does "a specific device" mean exactly what you said?
"

Yes.

**Comment by MichalMrozek** [comment] 2023-10-10 11:58
PVC devices would be grouped under single driver instance, so each PVC device will have separate address space and unique addresses.
Where UMD cannot guarantee this is when there are multiple drivers. This can happen on Windows when you have multiple devices with different generations , where each instance of the driver would be a seperate dll load.

This can happen on Linux as well when you load L0 and OCL drivers with single process, they do not coordinate the VA space.

Current driver model is that UMD is responsible for VA generation, UMD sees only its single loaded instance, if you load 2 x UMDs , they will not communicate with each other. 

Even within single driver instance you may have multiple different device generations, which will be grouped under different driver objects. Each driver represents one USM monolithic address space, but this doesn't happen across drivers instances.

**Comment by vinser52** [comment] 2023-10-10 14:38
Thank you @MichalMrozek for explanations. 

I have a technical question (mostly for my education). How does the GPU driver reserve the VA ranges for memory allocations? Should it make sure that OS will not use the same VAs for host allocations (e.g. regular malloc)? I believe that at least for `zeMemAllocHost` and `zeMemAllocHost` the driver should somehow synchronize with OS and other drivers.

**Comment by MichalMrozek** [comment] 2023-10-10 14:50
Yes for allocations that are CPU accessible (host/shared USM) it ensures there are no collisions within a process via reserving it in process CPU VA space.

**Comment by vinser52** [comment] 2023-10-10 14:58
> Yes for allocations that are CPU accessible (host/shared USM) it ensures there are no collisions within a process via reserving it in process CPU VA space.

But for device allocation how driver ensure no collisions with host allocations?

**Comment by MichalMrozek** [comment] 2023-10-10 15:03
They are allocated out of CPU inaccessible UMD driver managed range.

**Comment by jandres742** [comment] 2023-10-10 19:58
@vinser52 : was this 

> Does "a specific device" mean exactly what you said? Anyway I think it is a significant limitation and looks like it does not conform SYCL spec. Thoughts?

clarified with @MichalMrozek comments? or is there need for further clarification?

**Comment by bashbaug** [comment] 2023-10-10 20:19
In case it's helpful, and since this has come up in other contexts (pun not intended!), here's the way I think about this:

A usage that must work (and that is testable!) is that the USM query function must behave properly for all possible pointers, for a given context.  For Level Zero, this means if I call zeMemGetAllocProperties with a context and any pointer, the implementation needs to determine with 100% accuracy whether this is a USM pointer allocated against this context or whether this isn't.  If it is a USM pointer allocated against this context, the implementation needs to be able to lookup the properties of the USM pointer, such as its USM type, base address, size, etc.

Since host and shared USM pointers are host accessible they are guaranteed to be unique across contexts and even across drivers.  If they weren't, a USM pointer and a malloc'd pointer could have the same address and the query would not be accurate.

A device USM pointer is not host accessible though, so there is no guarantee device USM pointers will be unique across contexts or across devices.  One intuitive example how this could occur is if one driver assigns its device USM pointers outside of the host accessible VA range, and another driver (maybe even from a completely different device vendor) just so happens to assign its device USM pointers to the same range.

Hope this is helpful.  Note, I haven't read through this issue in detail, so I don't have much more to add beyond this.

**Comment by MichalMrozek** [comment] 2023-10-11 07:46
Thanks Ben, L0/OCL drivers works exactly as you described.

**Comment by irozanova** [comment] 2023-10-11 08:07
@bashbaug the problem is that there is no any mechanism for propagating context from one library to another. For example if OpenMP allocates some device memory, then other libraries cannot use this memory without context. Even if OpenMP can return us this context, then other libraries may not be able to get this context due to API limitations (MPI standard as example). 

So, getting context from the pointer is essential for multilibrary scenarios.


> if one driver assigns its device USM pointers outside of the host accessible VA range, and another driver (maybe even from a completely different device vendor) just so happens to assign its device USM pointers to the same range.

Is this a real use case? Why the user may need to use different drivers?

**Comment by vinser52** [comment] 2023-10-11 12:49
> clarified with @MichalMrozek comments? or is there need for further clarification?

Hi @jandres742,

The behavior of L0 is clear and we also clarified (internally) SYCL spec meaning. The conclusion is the device pointer (according to specs) is not unique within a process and cannot be used as a unique identifier (context is needed).

Now the question we are discussing is what higher-level runtimes can/should do with that.
In UMF we have memory-tracking capabilities that allow us to find the corresponding memory pool by pointer so that clients can request the property of that pool. The use case we have with MPI is that MPI wants by pointer find the context and request the IPC handle or any other properties of the pool. Now it seems that UMF tracking capabilities will only work in case of a single GPU driver.

The question is what should we do with that? We are trying to assess if such a use case is really practical and common enough. Perhaps on the UMF level, we can just return an error in such a case to tell the client that we have no tracking information. To be clear: return error only in case two allocations with the same VA happened and the user wants to find the appropriate memory pool by ptr.

At the next WG meeting, I am planning to discuss IPC functionality in UMF and touch that question. Please join it.

**Comment by jandres742** [comment] 2023-10-11 15:04
@irozanova 

> the problem is that there is no any mechanism for propagating context from one library to another. For example if OpenMP allocates some device memory, then other libraries cannot use this memory without context. Even if OpenMP can return us this context, then other libraries may not be able to get this context due to API limitations (MPI standard as example).
So, getting context from the pointer is essential for multilibrary scenarios.

Right. The proposal you shared before looks something we could add:

> zeMemGetAllocPropertiesExp(
    ze_driver_handle_t hDriver,                     ///< [in] handle of the driver object
    const void* ptr,                                ///< [in] memory pointer to query
    ze_memory_allocation_properties_t* pMemAllocProperties, ///< [in,out] query result for memory allocation properties
    ze_context_handle_t* phContext,                 ///< [out][optional] context associated with this allocation
    ze_device_handle_t* phDevice                    ///< [out][optional] device associated with this allocation
);

@wdamon-intel : what do you think?


@vinser52 Thanks for the details:

> The behavior of L0 is clear and we also clarified (internally) SYCL spec meaning. The conclusion is the device pointer (according to specs) is not unique within a process and cannot be used as a unique identifier (context is needed).

Right, and to clarify here: pointer is not unique within a process when you have multiple GPU drivers, especially from multiple vendors. But that's totally expected and I think that that would be what a user would expect. As you mention, one way to make it this work is with IPC mechanisms.

**Comment by MichalMrozek** [comment] 2023-10-11 15:13
How would driver implement this API ?
What would be returned if same pointer is allocated in 2 contexts?
What would be returned if same pointer is allocated in 2 devices?

**Comment by jandres742** [comment] 2023-10-11 15:27
@MichalMrozek to which API are you referring to? if you are referring to zeMemGetAllocPropertiesExp above, then the context returned there is the context used when the memory was allocated or used when the memory was imported. 

same pointer is not returned for 2 contexts of the same driver. A single driver has a single VA.
same pointer is not returned for 2 devices of the same driver. Same reason as above.

isn't that the case, @MichalMrozek , @bashbaug ?

**Comment by vinser52** [comment] 2023-10-12 12:30
@jandres742

> As you mention, one way to make it this work is with IPC mechanisms.

I did not get your point.

**Comment by MichalMrozek** [comment] 2023-10-12 12:42
"
same pointer is not returned for 2 contexts of the same driver. A single driver has a single VA.
"

No, you may mix PVC and DG2/intergrated and there will be collisions on device USM pointers.

"
same pointer is not returned for 2 devices of the same driver. Same reason as above.
"

No, this is not what Level Zero spec guarantees.

I don't see how we can reliably support this API in all cases.

**Comment by vinser52** [comment] 2023-10-12 13:27
> No, you may mix PVC and DG2/intergrated and there will be collisions on device USM pointers.

Does it mean we have two drivers?

> No, this is not what Level Zero spec guarantees.

Good point. It makes me think that the L0 spec is inconsistent.

On the one hand, the L0 spec says that "unified memory with a single virtual address space covering both the Host and (only) specific device". Does that mean that two devices in the same context might have the same VA space?

On the other hand, the L0 spec has the `zeMemGetAllocProperties` and `zeMemGetAddressRange` functions that accept context and pointer pair as unique identifiers.

If my understanding of the spec is correct should we fix it? Like was confirmed above our implementation provides a unified VA space for all devices supported by the driver.

**Comment by MichalMrozek** [comment] 2023-10-12 14:26
"
If my understanding of the spec is correct should we fix it? Like was confirmed above our implementation provides a unified VA space for all devices supported by the driver."

It is pretty clear that L0 spec has more limitations than SYCL spec and the pointer being unique requirement is not being satisfied, if you want to change it to have unique device USM we need broader discussion and would require substantial changes in the L0 specification and further driver implementations.

Please note that this may not be technically feasible in many cases to provide unique device USM pointers.

**Comment by vinser52** [comment] 2023-10-12 14:34
@MichalMrozek

the point in my previous message was not about consistency between L0 and SYCL, but about consistency of the L0 spec itself.
Let's forget about SYCL and our needs for now.

L0 spec says that "unified memory with a single virtual address space covering both the Host and (only) specific device". It sounds like if I will allocate device memory for two devices, but with the same context I can get the same VA.

**Comment by jandres742** [comment] 2023-10-12 15:07
@MichalMrozek if two devices (PVC and DG2) belong to different drivers, expectedly there might be VA collisions, and that's where IPC comes into place. But if they belong to the same driver (and even more if they belong to the same context), there shouldn't be any collisions, right? isn't that the essence of USM and P2P, that the pointers allocated on each device, under the same driver, belong to a single UVA, so that a pointer in a given device can be accessed from a peer device?

**Comment by MichalMrozek** [comment] 2023-10-12 15:30
"
But if they belong to the same driver (and even more if they belong to the same context), there shouldn't be any collisions, right"

Yes if 2 devices are in the same context, then no collisions are expected.
I wouldn't say this is also true if you have 2 separate context, in such case you may have collisions L0 spec wise.

**Comment by vinser52** [comment] 2023-10-12 17:04
> But if they belong to the same driver (and even more if they belong to the same context), there shouldn't be any collisions, right

But the spec does not guarantee that.

**Comment by jandres742** [comment] 2023-10-12 20:20
thanks @MichalMrozek . Let's discuss that internally. Whether the VA is at the driver or context level. as @vinser52  says, it is not clear in the spec, so we should clearly define it.

**Comment by wdamon-intel** [comment] 2024-01-31 17:22
Closing this Issue due to inactivity. A new, more complete proposal must be written if the functionality discussed here is still required.

**Closed by wdamon-intel** 2024-01-31 17:22 UTC
Labels: enhancement, API: Core, needs discussion
