### ISSUE TITLE
[Sysman]Report memory and GPU power

### ISSUE THREAD

**Issue by sanilkumar0** [oneapi-src/level-zero-spec#176] opened 2023-07-06 20:44 UTC
To display GPU and Memory power for ARC control GUI

**Comment by sanilkumar0** [comment] 2023-07-08 17:27
Add new sensor enum - zes_power_domain_t.ZES_POWER_DOMAIN_MEM and zes_power_domain_t.ZES_POWER_DOMAIN_GPU

**Comment by aravindksg** [comment] 2023-09-08 03:12
missed seeing this issue earlier, we could close this as duplicate of #214

**Closed** 2023-09-15 00:31 UTC
Labels: enhancement, API: Sysman
