### ISSUE TITLE
Add Sysman Event to detect if gfx driver goes offline

### ISSUE THREAD

**Issue by sanilkumar0** [oneapi-src/level-zero-spec#251] opened 2023-12-27 18:10 UTC
Add an event ZES_EVENT_TYPE_FLAG_SURVIVABIILTY_MODE_DETECTED to notify, if the gfx driver yellow bangs.

**Comment by aravindksg** [comment] 2024-01-03 17:59
Duplicate of #253

**Closed by aravindksg** 2024-01-03 17:59 UTC
Labels: API: Sysman
